export {default as Home} from './Home/Home'
export {default as Investment} from './Investment/Investment'
export {default as Support} from './Support/Support'
export {default as Settings} from './Settings/Settings'
export {default as Modal} from './Modal/Modal'